'use strict';
const {chromium}=require('/Users/jmartin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),path=require('node:path');
const near=(a,b,tol=1e-6)=>assert(Math.abs(a-b)<tol,a+' != '+b);
(async()=>{
 const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  await page.addInitScript(()=>{window.__frictionTools={};Object.defineProperty(document,'modelContext',{value:{registerTool(tool){window.__frictionTools[tool.name]=tool;}}});});
  await page.goto('file://'+path.resolve(__dirname,'../frottements_solides_webapp_fr.html'));
  await page.waitForFunction(()=>document.getElementById('loading').hidden);
  const read=()=>page.evaluate(()=>window.__frictionTools.read_friction_experiment.execute({}));
  const input=async(id,value)=>page.locator('#'+id).evaluate((el,value)=>{el.value=value;el.dispatchEvent(new Event('input',{bubbles:true}));},String(value));
  assert.equal(await page.locator('#force-mode').inputValue(),'manual');
  await input('duration',2);await page.selectOption('#force-mode','ramp');await input('ramp-rise',1);
  assert(await page.locator('#force').isDisabled());assert(await page.locator('#initial-speed').isDisabled());
  near((await read()).state.F,0);near((await read()).state.v1,0);
  await page.locator('#play').click();await page.waitForTimeout(240);await page.locator('#play').click();
  let s=(await read()).state;assert(s.t>0&&s.t<.654);assert.equal(s.mode,'static');near(s.f,-s.F);assert(Math.abs(s.f)<s.limit);
  near(s.F,15*s.t);near(s.x1,0);
  await page.locator('#play').click();await page.waitForFunction(()=>window.__frictionTools.read_friction_experiment.execute({}).state.t>1.2);
  await page.locator('#play').click();s=(await read()).state;assert.equal(s.mode,'kinetic');near(s.F,15);near(s.f,-5.886);near(s.balance,0);
  assert((await page.locator('#force-history').getAttribute('aria-label')).includes(s.F.toFixed(2)+' N'));
  assert(await page.locator('#chart-key').innerText());
  await page.locator('#history').press('Home');near((await read()).state.t,0);near((await read()).state.f,0);
  await page.locator('#play').click();await page.waitForTimeout(150);await page.locator('#play').click();
  assert((await read()).state.t>0);
  await page.locator('#replay-ramp').click();await page.waitForFunction(()=>window.__frictionTools.read_friction_experiment.execute({}).state.t>1.2);await page.locator('#play').click();
  await page.locator('#history').press('End');assert((await read()).state.t>1.2);
  await page.locator('#replay-ramp').click();s=(await read()).state;assert(s.t<.1);near(s.x1,0);assert((await read()).playing);
  await page.waitForFunction(()=>!window.__frictionTools.read_friction_experiment.execute({}).playing);
  s=(await read()).state;near(s.t,2);near(s.balance,0);
  await page.locator('#force-history').scrollIntoViewIfNeeded();
  await page.screenshot({path:path.resolve(__dirname,'../friction-ramp-desktop.png')});
  await page.locator('#force-history').screenshot({path:path.resolve(__dirname,'../friction-force-plot.png')});
  assert.equal(await page.locator('[data-mml-node="merror"]').count(),0);
  assert(await page.locator('#force-history-labels [data-number]').evaluateAll(els=>els.some(el=>!el.hidden&&el.dataset.number==='0|')));
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(200);
  await page.locator('#force-history').scrollIntoViewIfNeeded();
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.screenshot({path:path.resolve(__dirname,'../friction-ramp-mobile.png')});
  await page.selectOption('#model-select','incline');
  assert(!(await page.locator('#drive-control').isVisible()));assert(!(await page.locator('#force').isDisabled()));
  await input('angle',-35);assert((await read()).playing);await page.locator('#play').click();
  await page.selectOption('#model-select','stack');assert(!(await page.locator('#drive-control').isVisible()));
  await page.selectOption('#model-select','horizontal');await page.selectOption('#force-mode','ramp');
  await input('ramp-peak',5);await page.locator('#play').click();await page.waitForTimeout(150);await page.locator('#play').click();
  assert.equal((await read()).state.mode,'static');assert((await page.locator('#ramp-status').innerText()).includes('reste au repos'));
  await input('mu-static',.1);assert((await read()).playing);assert((await read()).state.t<.1);
  await page.locator('#play').click();await page.selectOption('#force-mode','manual');
  assert(!(await page.locator('#force').isDisabled()));assert(!(await page.locator('#initial-speed').isDisabled()));
  assert.deepEqual(errors,[]);
  console.log('PASS browser: ramp/rest/threshold/plateau, replay, seek, controls, MathJax, force graph, mobile, manual/incline/stack regressions.');
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
